### PR TITLE
Fix serving SVG images

### LINKED ISSUE #896: Make .png images work
`.png` images in our documentation do not render. It'd be nice if they did. I tested this with a fresh install of asciidoctor and they work just fine. This problem might have something to do with docbook.

### PR DESCRIPTION
**Pull request by nik9000**
We have to set the right mime type.

Closes #896

### CODE REVIEW

File: lib/ES/Util.pm [hunk 1]
```diff
@@ -794,11 +798,6 @@ http {
         add_header 'Access-Control-Allow-Headers' 'kbn-xsrf-token';
       }
     }
-    types {
-      text/html  html;
-      application/javascript  js;
-      text/css   css;
-    }
```
Comment (nik9000) [inline lib/ES/Util.pm]: These didn't do anything because nginx expects the proxied application to set the mime type.
