### PR TITLE
Teach Kibana link checking about PR features

### LINKED ISSUE #892: "Unified" PR checking fails on link problems from other projects
The "unified" PR checking that we have for the docs build started failing on bad links that were unrelated to the PR today:

<details><summary>The failure looked like this.</summary><div>

```
09:09:57 INFO:build_docs:Building docs
09:09:58 INFO:build_docs: -                        APM Node.js Agent: Building master...
09:10:00 INFO:build_docs: -                        APM Node.js Agent: Finished master
09:10:00 INFO:build_docs: -                        APM Node.js Agent: Writing versions TOC
09:10:03 INFO:build_docs:Writing main TOC
09:10:03 INFO:build_docs:Writing extra HTML redirects
09:10:03 INFO:build_docs:Writing nginx redirects
09:10:03 INFO:build_docs:Checking links
09:11:32 INFO:build_docs:Checking Kibana links
09:11:32 INFO:build_docs:  Branch 5.0
09:11:32 INFO:build_docs:  Branch 5.1
09:11:32 INFO:build_docs:  Branch 5.2
09:11:32 INFO:build_docs:  Branch 5.3
09:11:32 INFO:build_docs:  Branch 5.4
09:11:32 INFO:build_docs:  Branch 5.5
09:11:32 INFO:build_docs:  Branch 5.6
09:11:32 INFO:build_docs:  Branch 6.0
09:11:32 INFO:build_docs:  Branch 6.1
09:11:32 INFO:build_docs:  Branch 6.2
09:11:32 INFO:build_docs:  Branch 6.3
09:11:32 INFO:build_docs:  Branch 6.4
09:11:32 INFO:build_docs:  Branch 6.5
09:11:32 INFO:build_docs:  Branch 6.6
09:11:32 INFO:build_docs:  Branch 6.7
09:11:32 INFO:build_docs:  Branch 6.8
09:11:32 INFO:build_docs:  Branch 7.0
09:11:32 INFO:build_docs:  Branch 7.1
09:11:32 INFO:build_docs:  Branch 7.x
09:11:32 INFO:build_docs:  Branch master
09:11:32 INFO:build_docs:Bad cross-document links:
09:11:32 INFO:build_docs:  Kibana [master]: src/ui/public/documentation_links/documentation_links:
09:11:32 INFO:build_docs:   - en/siem/guide/master/index.html
```

</div></details>

<details><summary>The PR build executes this.</summary><div>

```
build_docs --all --keep_hash \
              --target_repo git@github.com:elastic/built-docs \
              --reference /var/lib/jenkins/.git-references \
              --sub_dir {repo}:${{ghprbTargetBranch}}:$(pwd)"
```

</div></details>

It looks like this can happen when kibana pushes a link to something that doesn't exist. We check those links, even on the PR builds. I suspect the simplest thing is to skip Kibana's link checking on those builds for now.....

### PR DESCRIPTION
**Pull request by nik9000**
The docs build has three features when building all books:
1. If you specify `--keep_hash` we reuse the hash of the source repos
for every book that we've built before. This is useful for rebuilding
only the books that we converted to asciidoctor. Or in combination with
`--sub_dir`
2. If you specify `--sub_dir` we use a directory instead of a commit
hash from some source repo. This is mostly useful in combination with
`--keep_hash` because when you use those together your can rebuild the
docs as though you committed the directory that you are subsituting. It
makes for perfect pull request tests.
3. We automatically check all of the links, including links from some
typescript files in the kibana repo.

The trouble is that the kibana repo link checking process didn't
understand `--keep_hash` and `--sub_dir`. This commit changes that. The
bulk of it the change is testing the link checking, which we didn't
really have any of up until now.

Closes #892

### CODE REVIEW

File: integtest/spec/all_books_broken_link_detection_spec.rb [hunk 1]
```diff
@@ -0,0 +1,212 @@
...
+    end
+  end
+  shared_context 'there is a broken link in kibana' do |check_links|
+    convert_before do |src, dest|
+      # Kibana is special and we check links in it with a little magic
+      kibana_repo = src.repo 'kibana'
+      kibana_repo.write KIBANA_LINKS_FILE, <<~JS
+        export const documentationLinks = {
+          foo: `${ELASTIC_WEBSITE_URL}guide/foo`,
+        };
```
Comment (estolfo) [inline integtest/spec/all_books_broken_link_detection_spec.rb]: I almost called out this semicolon but then realized this was javascript = )

**Comment by nik9000** [comment]
Thanks @estolfo and @olksdr !
